-- VERSIÓN UTILIZADA PARA LA CREACIÓN:
--Oracle AI Database 26ai Free Release 23.26.2.0.0 - Develop, Learn, and Run for Free

-- =========================================================
-- ELIMINACION DE OBJETOS
-- =========================================================

-- SECUENCIAS
DROP SEQUENCE IF EXISTS seq_compania;
DROP SEQUENCE IF EXISTS seq_comuna;

-- TABLAS
DROP TABLE IF EXISTS DOMINIO CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS TITULACION CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS PERSONAL CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS TITULO CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS GENERO CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS IDIOMA CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS ESTADO_CIVIL CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS COMPANIA CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS COMUNA CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS REGION CASCADE CONSTRAINTS;
-- CASO 1
CREATE TABLE REGION(
id_region NUMBER(2) GENERATED BY DEFAULT AS IDENTITY
    (START WITH 7 INCREMENT BY 2),
nombre_region VARCHAR2(25) NOT NULL,

CONSTRAINT region_pk PRIMARY KEY (id_region)
);

CREATE TABLE COMUNA(
id_comuna NUMBER(5),
comuna_nombre VARCHAR2(25) NOT NULL,
cod_region NUMBER(2) NOT NULL,

CONSTRAINT comuna_region_pk
PRIMARY KEY (id_comuna, cod_region),

CONSTRAINT comuna_region_fk
FOREIGN KEY (cod_region)
REFERENCES REGION(id_region)
);

CREATE TABLE COMPANIA(
id_empresa VARCHAR2(2),
nombre_empresa VARCHAR2(25) NOT NULL,
calle VARCHAR2(50) NOT NULL,
numeracion NUMBER(5) NOT NULL,
renta_promedio NUMBER(10) NOT NULL,
pct_aumento NUMBER(4,3),
cod_comuna NUMBER(5) NOT NULL,
cod_region NUMBER (2) NOT NULL,

CONSTRAINT compania_pk PRIMARY KEY (id_empresa),

CONSTRAINT compania_nombre_un
UNIQUE (nombre_empresa),

CONSTRAINT compania_comuna_region_fk
FOREIGN KEY (cod_comuna, cod_region)
REFERENCES COMUNA(id_comuna, cod_region)
);

CREATE TABLE ESTADO_CIVIL(
id_estado_civil VARCHAR2(2),
descripcion_est_civil VARCHAR2(25) NOT NULL,

CONSTRAINT estado_civil_pk PRIMARY KEY (id_estado_civil)
);

CREATE TABLE IDIOMA(
id_idioma NUMBER(3) GENERATED BY DEFAULT AS IDENTITY
    (START WITH 25 INCREMENT BY 3),
nombre_idioma VARCHAR2(30) NOT NULL,

CONSTRAINT idioma_pk PRIMARY KEY (id_idioma)
);

CREATE TABLE GENERO(
id_genero VARCHAR2(3),
descripcion_genero VARCHAR2(25) NOT NULL,

CONSTRAINT genero_pk PRIMARY KEY (id_genero)
);

CREATE TABLE TITULO(
id_titulo VARCHAR2(3),
descripcion_titulo VARCHAR2(60) NOT NULL,

CONSTRAINT titulo_pk PRIMARY KEY (id_titulo)
);

CREATE TABLE PERSONAL(
rut_persona NUMBER(8),
dv_persona CHAR(1) NOT NULL,
primer_nombre VARCHAR2(25) NOT NULL,
segundo_nombre VARCHAR2(25),
primer_apellido VARCHAR2(25) NOT NULL,
segundo_apellido VARCHAR2(25) NOT NULL,
fecha_contratacion DATE NOT NULL,
fecha_nacimiento DATE NOT NULL,
email VARCHAR2(100),
calle VARCHAR2(50) NOT NULL,
numeracion NUMBER(5) NOT NULL,
sueldo NUMBER(8) NOT NULL,
cod_comuna NUMBER(5) NOT NULL,
cod_region NUMBER(2) NOT NULL,
cod_genero VARCHAR2(3),
cod_estado_civil VARCHAR2(2),
cod_empresa VARCHAR2(2) NOT NULL,
encargado_rut NUMBER(8),

CONSTRAINT personal_pk PRIMARY KEY (rut_persona),

CONSTRAINT personal_comuna_region_fk
FOREIGN KEY (cod_comuna, cod_region)
REFERENCES COMUNA(id_comuna, cod_region),

CONSTRAINT personal_genero_fk
FOREIGN KEY (cod_genero)
REFERENCES GENERO(id_genero),

CONSTRAINT personal_est_civil_fk
FOREIGN KEY (cod_estado_civil)
REFERENCES ESTADO_CIVIL(id_estado_civil),

CONSTRAINT personal_empresa_fk
FOREIGN KEY (cod_empresa)
REFERENCES COMPANIA(id_empresa),

CONSTRAINT personal_personal_fk
FOREIGN KEY (encargado_rut)
REFERENCES PERSONAL(rut_persona)

);

CREATE TABLE TITULACION(
cod_titulo VARCHAR2(3),
persona_rut NUMBER(8),
fecha_titulacion DATE NOT NULL,

CONSTRAINT titulacion_pk
    PRIMARY KEY (cod_titulo, persona_rut),
    
CONSTRAINT titulacion_titulo_fk
FOREIGN KEY (cod_titulo)
REFERENCES TITULO(id_titulo),

CONSTRAINT titulacion_persona_fk
FOREIGN KEY (persona_rut)
REFERENCES PERSONAL(rut_persona)

);

CREATE TABLE DOMINIO(
id_idioma NUMBER(3),
persona_rut NUMBER(8),
nivel VARCHAR2(25) NOT NULL,

CONSTRAINT dominio_pk
    PRIMARY KEY (id_idioma, persona_rut),

CONSTRAINT dominio_idioma_fk
FOREIGN KEY (id_idioma)
REFERENCES IDIOMA(id_idioma),

CONSTRAINT dominio_personal_fk
FOREIGN KEY (persona_rut)
REFERENCES PERSONAL(rut_persona)
);

-- CASO 2
ALTER TABLE PERSONAL
ADD CONSTRAINT personal_email_un
UNIQUE (email);

ALTER TABLE PERSONAL
ADD CONSTRAINT personal_dv_ck
CHECK (dv_persona IN ('0','1','2','3','4','5','6','7','8','9','K'));

ALTER TABLE PERSONAL
ADD CONSTRAINT personal_sueldo_ck
CHECK (sueldo >= 450000);


-- CASO 3
-- INSERT DE REGIONES
INSERT INTO REGION (nombre_region)
VALUES ('ARICA Y PARINACOTA');

INSERT INTO REGION (nombre_region)
VALUES ('METROPOLITANA');

INSERT INTO REGION (nombre_region)
VALUES ('LA ARAUCANIA');

-- INSERT DE COMUNAS Y CREACIÓN DE SECUENCIA
CREATE SEQUENCE seq_comuna
START WITH 1101
INCREMENT BY 6
NOCYCLE;

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
VALUES (seq_comuna.NEXTVAL, 'Arica', 7);

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
VALUES (seq_comuna.NEXTVAL, 'Santiago', 9);

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
VALUES (seq_comuna.NEXTVAL, 'Temuco', 11);


-- INSERT DE IDIOMAS
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Ingles');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Chino');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Aleman');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Espanol');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Frances');

-- INSERT DE COMPANIAS
-- =========================================================
-- CASO 3: POBLAMIENTO DEL MODELO
-- =========================================================


-- ---------------------------------------------------------
-- REGION
-- Identity:
-- START WITH 7
-- INCREMENT BY 2
-- Generará: 7, 9, 11
-- ---------------------------------------------------------

INSERT INTO REGION (nombre_region)
VALUES ('ARICA Y PARINACOTA');

INSERT INTO REGION (nombre_region)
VALUES ('METROPOLITANA');

INSERT INTO REGION (nombre_region)
VALUES ('LA ARAUCANIA');


-- ---------------------------------------------------------
-- COMUNA
-- Secuencia:
-- START WITH 1101
-- INCREMENT BY 6
-- Generará: 1101, 1107, 1113
-- ---------------------------------------------------------

CREATE SEQUENCE seq_comuna
START WITH 1101
INCREMENT BY 6
NOCYCLE;

INSERT INTO COMUNA (
    id_comuna,
    comuna_nombre,
    cod_region
)
VALUES (
    seq_comuna.NEXTVAL,
    'Arica',
    7
);

INSERT INTO COMUNA (
    id_comuna,
    comuna_nombre,
    cod_region
)
VALUES (
    seq_comuna.NEXTVAL,
    'Santiago',
    9
);

INSERT INTO COMUNA (
    id_comuna,
    comuna_nombre,
    cod_region
)
VALUES (
    seq_comuna.NEXTVAL,
    'Temuco',
    11
);


-- ---------------------------------------------------------
-- IDIOMA
-- Identity:
-- START WITH 25
-- INCREMENT BY 3
-- Generará: 25, 28, 31, 34, 37
-- ---------------------------------------------------------

INSERT INTO IDIOMA (nombre_idioma)
VALUES ('Ingles');

INSERT INTO IDIOMA (nombre_idioma)
VALUES ('Chino');

INSERT INTO IDIOMA (nombre_idioma)
VALUES ('Aleman');

INSERT INTO IDIOMA (nombre_idioma)
VALUES ('Espanol');

INSERT INTO IDIOMA (nombre_idioma)
VALUES ('Frances');


-- ---------------------------------------------------------
-- COMPANIA
-- Secuencia:
-- START WITH 10
-- INCREMENT BY 5
-- Generará: 10, 15, 20, ..., 55
-- ---------------------------------------------------------

CREATE SEQUENCE seq_compania
START WITH 10
INCREMENT BY 5
NOCYCLE;


INSERT INTO COMPANIA (
    id_empresa,
    nombre_empresa,
    calle,
    numeracion,
    renta_promedio,
    pct_aumento,
    cod_comuna,
    cod_region
)
VALUES (
    TO_CHAR(seq_compania.NEXTVAL),
    'CCyRojas',
    'Amapolas',
    506,
    1857000,
    0.5,
    1101,
    7
);


INSERT INTO COMPANIA (
    id_empresa,
    nombre_empresa,
    calle,
    numeracion,
    renta_promedio,
    pct_aumento,
    cod_comuna,
    cod_region
)
VALUES (
    TO_CHAR(seq_compania.NEXTVAL),
    'SenTTy',
    'Los Alamos',
    3490,
    897000,
    0.025,
    1101,
    7
);


INSERT INTO COMPANIA (
    id_empresa,
    nombre_empresa,
    calle,
    numeracion,
    renta_promedio,
    pct_aumento,
    cod_comuna,
    cod_region
)
VALUES (
    TO_CHAR(seq_compania.NEXTVAL),
    'Praxia LTDA',
    'Las Camelias',
    11098,
    2157000,
    0.035,
    1107,
    9
);


INSERT INTO COMPANIA (
    id_empresa,
    nombre_empresa,
    calle,
    numeracion,
    renta_promedio,
    pct_aumento,
    cod_comuna,
    cod_region
)
VALUES (
    TO_CHAR(seq_compania.NEXTVAL),
    'TIC spa',
    'FLORES S.A.',
    4357,
    857000,
    NULL,
    1107,
    9
);


INSERT INTO COMPANIA (
    id_empresa,
    nombre_empresa,
    calle,
    numeracion,
    renta_promedio,
    pct_aumento,
    cod_comuna,
    cod_region
)
VALUES (
    TO_CHAR(seq_compania.NEXTVAL),
    'SANTANA LTDA',
    'AVDA VIC. MACKENA',
    106,
    757000,
    0.015,
    1101,
    7
);


INSERT INTO COMPANIA (
    id_empresa,
    nombre_empresa,
    calle,
    numeracion,
    renta_promedio,
    pct_aumento,
    cod_comuna,
    cod_region
)
VALUES (
    TO_CHAR(seq_compania.NEXTVAL),
    'FLORES Y ASOCIADOS',
    'PEDRO LATORRE',
    557,
    589000,
    0.015,
    1107,
    9
);


INSERT INTO COMPANIA (
    id_empresa,
    nombre_empresa,
    calle,
    numeracion,
    renta_promedio,
    pct_aumento,
    cod_comuna,
    cod_region
)
VALUES (
    TO_CHAR(seq_compania.NEXTVAL),
    'J.A. HOFFMAN',
    'LATINA D.32',
    509,
    1857000,
    0.025,
    1113,
    11
);


INSERT INTO COMPANIA (
    id_empresa,
    nombre_empresa,
    calle,
    numeracion,
    renta_promedio,
    pct_aumento,
    cod_comuna,
    cod_region
)
VALUES (
    TO_CHAR(seq_compania.NEXTVAL),
    'CAGLIARI D.',
    'ALAMEDA',
    206,
    1857000,
    NULL,
    1107,
    9
);


INSERT INTO COMPANIA (
    id_empresa,
    nombre_empresa,
    calle,
    numeracion,
    renta_promedio,
    pct_aumento,
    cod_comuna,
    cod_region
)
VALUES (
    TO_CHAR(seq_compania.NEXTVAL),
    'Rojas HNOS LTDA',
    'SUCRE',
    106,
    957000,
    0.005,
    1113,
    11
);


INSERT INTO COMPANIA (
    id_empresa,
    nombre_empresa,
    calle,
    numeracion,
    renta_promedio,
    pct_aumento,
    cod_comuna,
    cod_region
)
VALUES (
    TO_CHAR(seq_compania.NEXTVAL),
    'FRIENDS P. S.A',
    'SUECIA',
    506,
    857000,
    0.015,
    1113,
    11
);

COMMIT;

-- =========================================================
-- CASO 4
-- INFORME 1: SIMULACION DE RENTA PROMEDIO
-- =========================================================

SELECT
    nombre_empresa AS "Nombre Empresa",
    calle || ' ' || numeracion AS "Dirección",
    renta_promedio AS "Renta Promedio",
    renta_promedio + (renta_promedio * pct_aumento) AS "Simulación de Renta"
FROM COMPANIA
ORDER BY
    renta_promedio DESC,
    nombre_empresa ASC;
    
    
-- =========================================================
-- INFORME 2: NUEVA SIMULACION DE RENTA PROMEDIO
-- =========================================================

SELECT
    id_empresa AS "CODIGO",
    nombre_empresa AS "EMPRESA",
    renta_promedio AS "PROM RENTA ACTUAL",
    pct_aumento + 0.15 AS "PCT AUMENTADO EN 15%",
    renta_promedio * (pct_aumento + 0.15) AS "RENTA AUMENTADA"
FROM COMPANIA
ORDER BY
    renta_promedio ASC,
    nombre_empresa DESC;
